### ISSUE TITLE
1st row seem to be repeated on visualization

### ISSUE THREAD

**Issue by aptoptout** [davidpb90/Visualizing-Books#1]
When looking at the first visual result it seems that the 1st row of the table is being repeated until the end. Most likely an error in the nested for loops when initializing the flow field.

**Comment by davidpb90** [comment]
When calling the sentiment we need to iterate over the full vector length, not just the square root, thus
I replaced i -> i*rows + j. Trying to run it said that resolution, cols and rows were not defined, so I just defined them as 1, 1000, 1000 respectively as a trial, obtaining a final image without repeated rows. Where are those variables coming from?

**Comment by aptoptout** [comment]
Amazing, thank you. Overlooked that part. Yes it seems to be running well now. Going to work on the particles now.

Ah yes sorry that was still some pseudo code on how the function needs to work like when we are initializing the particles on the flow field. They (the particles) will need a look-up function to "see" the vector at that spot in the flow field.
