### ISSUE TITLE
Repeating words

### ISSUE THREAD

**Issue by aptoptout** [davidpb90/Visualizing-Books#28]
Currently we have a lot of words that have multiple sentiments, how do we deal with those?

**Comment by aptoptout** [comment]
We should somehow stack them and take the average from all of them.

**Comment by davidpb90** [comment]
Great idea, but then do we want to have the mapping directly in the database? I.e. I can provide the table with the forces already there, but I feel that would slow tinkering down. Another option is for me to stack all the sentiments for a word in a single row and then we can do the calculation in js extracting them. The latter sounds better to me.

**Comment by aptoptout** [comment]
The last option you suggest sounds good. We could also stack multiple instances of a word on the frontend, leaving the data as the data which I can imagine would be our main goal for the database.

but if the last option doesn't come with much side effects it would improve on performance for sure!
